{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.2054.0 (24.12)+334ca1c95b576cc53924655643b0d36f21caac55"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Store\",\"Sales\",\"Item\",\"Time\",\"District\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "asdf": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Time"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "time": {}
                  }
                ]
              },
              "asdf.business_day_date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Time",
                    "ConceptualProperty": "Month"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "business day date": {}
                  }
                ]
              },
              "asdf.calendar_year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Time",
                    "ConceptualProperty": "Year"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "calendar year": {}
                  },
                  {
                    "year": {}
                  }
                ]
              },
              "asdf.fiscal_month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Time",
                    "ConceptualProperty": "FiscalMonth"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "fiscal month": {}
                  },
                  {
                    "month": {}
                  }
                ]
              },
              "asdf.fiscal_year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Time",
                    "ConceptualProperty": "FiscalYear"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "fiscal year": {}
                  },
                  {
                    "year": {}
                  }
                ]
              },
              "asdf.period": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Time",
                    "ConceptualProperty": "Period"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "period": {}
                  }
                ]
              },
              "asdf.reporting_period_ID": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Time",
                    "ConceptualProperty": "ReportingPeriodID"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "reporting period ID": {}
                  }
                ]
              },
              "asdf.row_number": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Time",
                    "ConceptualProperty": "RowNumber"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "row number": {}
                  }
                ]
              },
              "sales.totalsalesty": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sales",
                    "ConceptualProperty": "TotalSalesTY"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "This Year Sales": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "store": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "store": {}
                  }
                ]
              },
              "store.DM": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "DM"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "DM": {}
                  }
                ]
              },
              "store.DM_pic": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "DM_Pic"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "DM pic": {}
                  }
                ]
              },
              "store.ITU_country_code": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "ITUCountryCode"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ITU country code": {}
                  }
                ]
              },
              "store.address": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "Address"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "address": {}
                  }
                ]
              },
              "store.address_line_1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "AddressLine1"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "address line 1": {}
                  }
                ]
              },
              "store.address_line_2": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "AddressLine2"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "address line 2": {}
                  }
                ]
              },
              "store.address_line_3": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "AddressLine3"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "address line 3": {}
                  }
                ]
              },
              "store.address_line_4": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "AddressLine4"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "address line 4": {}
                  }
                ]
              },
              "store.area_size_unitof_measure_code": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "AreaSizeUnitofMeasureCode"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "area size unitof measure code": {}
                  }
                ]
              },
              "store.area_unit_of_measure_name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "AreaUnitOfMeasureName"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "area unit of measure name": {}
                  }
                ]
              },
              "store.average_of_selling_area_size": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "Average Selling Area Size"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "average selling area size": {}
                  },
                  {
                    "average of selling area size": {}
                  }
                ]
              },
              "store.business_unit_ID": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "BusinessUnitID"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "business unit ID": {}
                  }
                ]
              },
              "store.business_unit_type_code": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "BusinessUnitTypeCode"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "business unit type code": {}
                  }
                ]
              },
              "store.calculated_column_1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "City"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "city": {}
                  },
                  {
                    "calculated column 1": {}
                  }
                ]
              },
              "store.calculated_column_11": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "Open Year"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "open year": {}
                  },
                  {
                    "calculated column 1": {}
                  }
                ]
              },
              "store.calculated_column_12": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "Store Type"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "store type": {}
                  },
                  {
                    "calculated column 1": {}
                  }
                ]
              },
              "store.calculated_column_13": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "Open Month No"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "open month no": {}
                  },
                  {
                    "open month": {}
                  },
                  {
                    "calculated column 1": {}
                  }
                ]
              },
              "store.calculated_column_14": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "Open Month"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "open month": {}
                  },
                  {
                    "calculated column 1": {}
                  }
                ]
              },
              "store.chain": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "Chain"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "chain": {}
                  }
                ]
              },
              "store.city": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "City Name"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "city name": {}
                  },
                  {
                    "city": {}
                  }
                ]
              },
              "store.closing_date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "ClosingDate"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "closing date": {}
                  }
                ]
              },
              "store.complete_number": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "CompleteNumber"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "complete number": {}
                  }
                ]
              },
              "store.count_of_open_date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "Count of OpenDate"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "count of open date": {}
                  }
                ]
              },
              "store.count_of_open_date_2": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "Open Store Count"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "open store count": {}
                  },
                  {
                    "count of open date 2": {}
                  }
                ]
              },
              "store.count_of_store_number_name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "Total Stores"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "total store": {}
                  },
                  {
                    "count of store number name": {}
                  }
                ]
              },
              "store.district_ID": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "DistrictID"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "district ID": {}
                  }
                ]
              },
              "store.district_name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "DistrictName"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "district name": {}
                  },
                  {
                    "district": {}
                  }
                ]
              },
              "store.email_address": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "EmailAddress"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "email address": {}
                  }
                ]
              },
              "store.function_code": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "FunctionCode"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "function code": {}
                  }
                ]
              },
              "store.inventory_location_ID": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "InventoryLocationID"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "inventory location ID": {}
                  }
                ]
              },
              "store.last_remodel_date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "LastRemodelDate"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "last remodel date": {}
                  }
                ]
              },
              "store.latitude": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "Latitude"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "latitude": {}
                  }
                ]
              },
              "store.location_ID": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "LocationID"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "location ID": {}
                  }
                ]
              },
              "store.longitude": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "Longitude"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "longitude": {}
                  }
                ]
              },
              "store.market_area_ID": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "MarketAreaID"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "market area ID": {}
                  }
                ]
              },
              "store.market_area_name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "MarketAreaName"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "market area name": {}
                  }
                ]
              },
              "store.market_region_ID": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "MarketRegionID"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "market region ID": {}
                  }
                ]
              },
              "store.market_region_name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "MarketRegionName"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "market region name": {}
                  }
                ]
              },
              "store.name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "Name"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "name": {}
                  }
                ]
              },
              "store.new_store": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "New Stores"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "new store": {}
                  }
                ]
              },
              "store.new_stores_target": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "New Stores Target"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "new stores target": {}
                  }
                ]
              },
              "store.open_date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "OpenDate"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "open date": {}
                  }
                ]
              },
              "store.postal_code": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "PostalCode"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "postal code": {}
                  },
                  {
                    "zip": {}
                  }
                ]
              },
              "store.postal_code_extension": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "PostalCodeExtension"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "postal code extension": {}
                  }
                ]
              },
              "store.row_number": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "RowNumber"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "row number": {}
                  }
                ]
              },
              "store.security_class_code": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "SecurityClassCode"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "security class code": {}
                  }
                ]
              },
              "store.selling_area_size": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "SellingAreaSize"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "selling area size": {}
                  }
                ]
              },
              "store.site_ID": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "SiteID"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "site ID": {}
                  }
                ]
              },
              "store.size": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "Size"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "size": {}
                  }
                ]
              },
              "store.store_group_ID": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "StoreGroupID"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "store group ID": {}
                  }
                ]
              },
              "store.store_group_name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "StoreGroupName"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "store group name": {}
                  }
                ]
              },
              "store.store_number": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "StoreNumber"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "store number": {}
                  }
                ]
              },
              "store.store_number_name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "StoreNumberName"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "store number name": {}
                  }
                ]
              },
              "store.territory": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Store",
                    "ConceptualProperty": "Territory"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "territory": {}
                  },
                  {}
                ]
              }
            },
            "Language": "en-US",
            "Version": "2.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "3eef198b-ca6c-4ee3-a0bd-9e35b5c725b8",
        "fromColumn": "DistrictID",
        "fromTable": "Store",
        "toColumn": "DistrictID",
        "toTable": "District"
      },
      {
        "name": "4e8a6ba0-ddf4-46af-996a-c4b2b4dbe2bf",
        "fromColumn": "LocationID",
        "fromTable": "Sales",
        "toColumn": "LocationID",
        "toTable": "Store"
      },
      {
        "name": "e16ca2b4-d139-4ef8-9a00-5b7616ecc5ac",
        "fromColumn": "ItemID",
        "fromTable": "Sales",
        "toColumn": "ItemID",
        "toTable": "Item"
      },
      {
        "name": "d3e1e755-e88f-4569-bd13-f1041030ae98",
        "fromColumn": "ReportingPeriodID",
        "fromTable": "Sales",
        "toColumn": "ReportingPeriodID",
        "toTable": "Time"
      },
      {
        "name": "74e52eb9-ac73-4b07-bb52-1b4cca072b32",
        "fromColumn": "OpenDate",
        "fromTable": "Store",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_0eafa36c-5fc2-4b6f-84df-278a77695bc4"
      },
      {
        "name": "ffdea654-6956-479d-9b81-f720c4647966",
        "fromColumn": "Month",
        "fromTable": "Time",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2403841f-d1ed-4123-bf26-4ba8066f16d8"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Store",
        "annotations": [
          {
            "name": "__PBI_SemanticLinks",
            "value": "[{\"LinkTarget\":{\"TableName\":\"Item\",\"TableItemName\":\"Category (clusters) 2\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
          }
        ],
        "columns": [
          {
            "name": "LocationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "d88dc5fb-f521-480c-83ce-7afc24fb5124",
            "sourceColumn": "LocationID",
            "summarizeBy": "none"
          },
          {
            "name": "City Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "78d437bf-c366-4939-a6ba-f647a6fc185f",
            "sourceColumn": "City Name",
            "summarizeBy": "none"
          },
          {
            "name": "Territory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "lineageTag": "d65e7eb7-1bad-4eba-8b5c-9d2a8099beee",
            "sourceColumn": "Territory",
            "summarizeBy": "none"
          },
          {
            "name": "PostalCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Item\",\"TableItemName\":\"Category (clusters) 2\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataCategory": "PostalCode",
            "dataType": "string",
            "lineageTag": "64a19c9f-97ec-4c28-9491-d7e9c0908460",
            "sourceColumn": "PostalCode",
            "summarizeBy": "none"
          },
          {
            "name": "OpenDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "c7615f0e-a376-4b14-959a-fae6f7f78072",
            "sourceColumn": "OpenDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_0eafa36c-5fc2-4b6f-84df-278a77695bc4"
                },
                "isDefault": true,
                "relationship": "74e52eb9-ac73-4b07-bb52-1b4cca072b32"
              }
            ]
          },
          {
            "name": "SellingAreaSize",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "25dfc9ea-95a3-49c6-a17d-ab892084ed28",
            "sourceColumn": "SellingAreaSize",
            "summarizeBy": "sum"
          },
          {
            "name": "DistrictName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "01221944-8dcd-4885-928a-998edf602727",
            "sourceColumn": "DistrictName",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47196cfa-ca7a-4529-a65f-0b22c05b1f8d",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "StoreNumberName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDefaultLabel": true,
            "lineageTag": "9b6ad4d6-64d5-46b0-bd6b-f5acca41eafb",
            "sourceColumn": "StoreNumberName",
            "summarizeBy": "none",
            "tableDetailPosition": 0
          },
          {
            "name": "StoreNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "47dc55a3-0215-435d-9920-c16ada4eb4ab",
            "sourceColumn": "StoreNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City",
            "dataType": "string",
            "expression": "[City Name] & \", \"&[Territory]",
            "isDataTypeInferred": true,
            "lineageTag": "9916b52e-c253-4676-ad00-2ce73b864c3b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Chain",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "37259bfb-911c-4568-85ef-91a69d351cf5",
            "sourceColumn": "Chain",
            "summarizeBy": "none"
          },
          {
            "name": "DM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03782db7-df58-4363-94d2-38a6eabad75e",
            "sourceColumn": "DM",
            "summarizeBy": "none"
          },
          {
            "name": "DM_Pic",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "2f3622ba-7ee7-45fd-8d23-2319527679c2",
            "sourceColumn": "DM_Pic",
            "summarizeBy": "none"
          },
          {
            "name": "DistrictID",
            "dataType": "int64",
            "lineageTag": "9f76763d-0f5b-42ab-875c-90aac4331d9d",
            "sourceColumn": "DistrictID",
            "summarizeBy": "none"
          },
          {
            "name": "Open Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR([OpenDate])",
            "isDataTypeInferred": true,
            "lineageTag": "b9328ca3-4eff-4bbe-b55b-1665de13ea35",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Store Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Item\",\"TableItemName\":\"Category (clusters) 2\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "string",
            "expression": "IF([Open Year]=2014, \"New Store\", \"Same Store\")",
            "isDataTypeInferred": true,
            "lineageTag": "307f2a8b-8a05-4ccb-846f-5c417b528f57",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Open Month No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH([OpenDate])",
            "isDataTypeInferred": true,
            "lineageTag": "448890ad-ad5e-46aa-ac6b-3c5f11017dad",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Open Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT([OpenDate], \"MMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "ec6705ae-e510-4e4f-adc3-385e3b2667c0",
            "sortByColumn": "Open Month No",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "0862204f-8f7e-49e5-b8ef-9ec0e9d8569d",
        "measures": [
          {
            "name": "Average Selling Area Size",
            "expression": "AVERAGE([SellingAreaSize])",
            "formatString": "#,0",
            "lineageTag": "d4d8be7f-1baa-48a1-bf61-f2647049ffa3"
          },
          {
            "name": "New Stores",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(COUNTA([Store Type]), FILTER(ALL(Store), [Store Type]=\"New Store\"))",
            "lineageTag": "ac544d84-fd6b-475b-973a-69c387496cca"
          },
          {
            "name": "New Stores Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "14",
            "lineageTag": "4087871e-363a-469e-b45d-707dd02bfa89"
          },
          {
            "name": "Total Stores",
            "expression": "COUNTA([StoreNumberName])",
            "formatString": "0",
            "lineageTag": "2e7df479-c5cd-410e-905a-b89480f7f9f8"
          },
          {
            "name": "Open Store Count",
            "expression": "COUNTA([OpenDate])",
            "formatString": "0",
            "lineageTag": "30cee895-9cf3-4f03-82c9-b0295fc9ff14"
          },
          {
            "name": "Count of OpenDate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "COUNTA('Store'[OpenDate])",
            "lineageTag": "c5c2edee-1f9b-42c2-a823-052a180088a6"
          }
        ],
        "partitions": [
          {
            "name": "Store",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"RetailBIDW\", [Query=\"select * from ip.retail.StoreDim\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"LocationID\", \"LocationID\"}, {\"City\", \"City Name\"}, {\"Territory\", \"Territory\"}, {\"PostalCode\", \"PostalCode\"}, {\"OpenDate\", \"OpenDate\"}, {\"SellingAreaSize\", \"SellingAreaSize\"}, {\"DistrictName\", \"DistrictName\"}, {\"Name\", \"Name\"}, {\"StoreNumberName\", \"StoreNumberName\"}, {\"StoreNumber\", \"StoreNumber\"}, {\"Chain\", \"Chain\"}, {\"DM\", \"DM\"}, {\"DM_Pic\", \"DM_Pic\"}, {\"DistrictID\", \"DistrictID\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"LocationID\", Int64.Type}, {\"City Name\", type text}, {\"Territory\", type text}, {\"PostalCode\", type text}, {\"OpenDate\", type datetime}, {\"SellingAreaSize\", Int64.Type}, {\"DistrictName\", type text}, {\"Name\", type text}, {\"StoreNumberName\", type text}, {\"StoreNumber\", Int64.Type}, {\"Chain\", type text}, {\"DM\", type text}, {\"DM_Pic\", type text}, {\"DistrictID\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales",
        "annotations": [
          {
            "name": "__PBI_SemanticLinks",
            "value": "[{\"LinkTarget\":{\"TableName\":\"Item\",\"TableItemName\":\"Category (clusters) 2\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
          }
        ],
        "columns": [
          {
            "name": "MonthID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "baab3ccb-a5ff-4517-8c31-7e6f7a3e0e2b",
            "sourceColumn": "MonthID",
            "summarizeBy": "count"
          },
          {
            "name": "ItemID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "3853282e-2a0c-4a36-ac4c-ff4ce0aba510",
            "sourceColumn": "ItemID",
            "summarizeBy": "none"
          },
          {
            "name": "LocationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "c62b04a9-e442-4fd6-8f61-f7d8b537c9b3",
            "sourceColumn": "LocationID",
            "summarizeBy": "none"
          },
          {
            "name": "Sum_GrossMarginAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "07cbb4f5-e176-4525-938e-d8af1d6b5b23",
            "sourceColumn": "Sum_GrossMarginAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "Sum_Regular_Sales_Dollars",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "d5374e80-00f1-466c-a274-6b3cc51d9443",
            "sourceColumn": "Sum_Regular_Sales_Dollars",
            "summarizeBy": "sum"
          },
          {
            "name": "Sum_Markdown_Sales_Dollars",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "1f3e455b-8050-4033-8de2-77264b5ecbd1",
            "sourceColumn": "Sum_Markdown_Sales_Dollars",
            "summarizeBy": "sum"
          },
          {
            "name": "ScenarioID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "b6908274-3bd5-4b34-b81c-eff659be3788",
            "sourceColumn": "ScenarioID",
            "summarizeBy": "count"
          },
          {
            "name": "ReportingPeriodID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "[MonthID]&\"01\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f96c3082-dfd8-4e0c-842b-563a8fd46899",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sum_Regular_Sales_Units",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "7d34a1e2-4729-420b-a693-71c2b26b3744",
            "sourceColumn": "Sum_Regular_Sales_Units",
            "summarizeBy": "sum"
          },
          {
            "name": "Sum_Markdown_Sales_Units",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "815bad44-11e0-4d8f-b83a-e68aaf4866d0",
            "sourceColumn": "Sum_Markdown_Sales_Units",
            "summarizeBy": "sum"
          }
        ],
        "isHidden": true,
        "lineageTag": "d14a8b76-0b9b-4daf-9df5-064bdb47e7fa",
        "measures": [
          {
            "name": "Regular_Sales_Dollars",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM([Sum_Regular_Sales_Dollars])",
            "lineageTag": "4eead230-877e-4b3c-84d9-88e3c872ddf1"
          },
          {
            "name": "Markdown_Sales_Dollars",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM([Sum_Markdown_Sales_Dollars])",
            "lineageTag": "701f562d-0e6c-4fa3-b026-10d9d0f73a20"
          },
          {
            "name": "TotalSales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Regular_Sales_Dollars]+[Markdown_Sales_Dollars]",
            "lineageTag": "f260b8d5-afd7-49da-a807-c91a810699af"
          },
          {
            "name": "TotalSalesLY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "CALCULATE([TotalSales], Sales[ScenarioID]=2)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "5d66fb8f-f6f9-4bbb-bc9d-2b6cd0175b6e"
          },
          {
            "name": "Gross Margin This Year",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "CALCULATE(SUM([Sum_GrossMarginAmount]), Sales[ScenarioID]=1)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "07bf192d-51d4-4c5e-9ace-3483e93553bc"
          },
          {
            "name": "Gross Margin This Year %",
            "expression": "[Gross Margin This Year]/[TotalSalesTY]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "5f7b86d7-d266-4dc7-be3d-d0e3fae4e17c"
          },
          {
            "name": "Gross Margin Last Year",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "CALCULATE(SUM([Sum_GrossMarginAmount]), Sales[ScenarioID]=2)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "8581ccb3-df82-418b-82de-116bc0f356ba"
          },
          {
            "name": "Gross Margin Last Year %",
            "expression": "[Gross Margin Last Year]/[TotalSalesLY]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "5bc65f34-eb45-471d-9300-d073c0f2212e"
          },
          {
            "name": "Regular_Sales_Units",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM([Sum_Regular_Sales_Units])",
            "lineageTag": "f200ec42-04a3-412e-a344-7b01f0c17a8c"
          },
          {
            "name": "Markdown_Sales_Units",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM([Sum_Markdown_Sales_Units])",
            "lineageTag": "e5a07e52-4418-4bfe-ba26-ec7da49505c6"
          },
          {
            "name": "TotalUnits",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Regular_Sales_Units]+[Markdown_Sales_Units]",
            "lineageTag": "b269d0ea-8e1d-473c-b3b2-e6f367d0262b"
          },
          {
            "name": "Total Units Last Year",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "CALCULATE([TotalUnits], Sales[ScenarioID]=2)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "9b620973-d7dc-4615-8715-0c7d494def8f"
          },
          {
            "name": "Total Units This Year",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "CALCULATE([TotalUnits], Sales[ScenarioID]=1)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "fc2c6460-f275-45af-881f-f3f15ce05042"
          },
          {
            "name": "Avg $/Unit TY",
            "annotations": [
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Item\",\"TableItemName\":\"Category (clusters) 2\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "IF([Total Units This Year]<>0, [TotalSalesTY]/[Total Units This Year], BLANK())",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "00d193e4-3abb-40b3-8e53-26bfdd7ad89c"
          },
          {
            "name": "Avg $/Unit LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "IF([Total Units Last Year]<>0, [TotalSalesLY]/[Total Units Last Year], BLANK())",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "d1eb5dd6-143e-4765-8289-8ae8b2dd6719"
          },
          {
            "name": "Total Sales Var",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "[TotalSalesTY]-[TotalSalesLY]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "65306a23-e8f7-4306-ac67-e7cd12ecc2d9"
          },
          {
            "name": "Total Sales Var %",
            "expression": "IF([TotalSalesLY]<>0, [Total Sales Var]/[TotalSalesLY], BLANK())",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2865ae74-6bbd-4c52-8d88-43728c1a939f"
          },
          {
            "name": "Sales Per Sq Ft",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "([TotalSalesTY]/(DISTINCTCOUNT([MonthID])*SUM(Store[SellingAreaSize])))*12",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "c186b2e3-4d3e-4e4e-acbc-3b077e7b2dc9"
          },
          {
            "name": "Last Year Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "[TotalSalesLY]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "45ac21b1-6762-477b-9f28-34af91f41b93"
          },
          {
            "name": "Total Sales Variance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "[Total Sales Var]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "59da46ac-f0aa-4eb2-9731-dd64641a131d"
          },
          {
            "name": "Total Sales Variance %",
            "annotations": [
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Item\",\"TableItemName\":\"Category (clusters) 2\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "expression": "[Total Sales Var %]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "636e039f-be99-4bc2-9bb0-6cd5a812b9ac"
          },
          {
            "name": "Store Count",
            "expression": "DISTINCTCOUNT([LocationID])",
            "formatString": "0",
            "lineageTag": "1804bc3a-a1e6-461a-b001-13e43de810b2"
          },
          {
            "name": "Average Unit Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "[Avg $/Unit TY]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "3fee08d0-031c-47fa-aef5-13e4fad10528"
          },
          {
            "name": "Average Unit Price Last Year",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "[Avg $/Unit LY]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "3dc89775-3219-4c25-906e-548f73ba6aa1"
          },
          {
            "name": "TotalSalesTY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "CALCULATE([TotalSales], Sales[ScenarioID]=1)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "kpi": {
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "Measure"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Percentage"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "95"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "100"
                }
              ],
              "statusExpression": [
                "var x='Sales'[TotalSalesTY]/'Sales'[_TotalSalesTY Goal] return",
                "if(ISBLANK(x),BLANK(),",
                "        If(x<0.95,-1,",
                "\t    If(x<1,0,1)",
                "    )",
                ")",
                ""
              ],
              "statusGraphic": "Traffic Light - Single",
              "targetExpression": "'Sales'[TotalSalesLY]",
              "targetFormatString": "\\$#,0;(\\$#,0);\\$#,0"
            },
            "lineageTag": "c7c793be-75ee-432c-8643-0a246531b565"
          },
          {
            "name": "This Year Sales",
            "annotations": [
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Item\",\"TableItemName\":\"Category (clusters) 2\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "[TotalSalesTY]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "kpi": {
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "Measure"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Percentage"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "95"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "100"
                }
              ],
              "statusExpression": [
                "var x='Sales'[This Year Sales]/'Sales'[_This Year Sales Goal] return",
                "if(ISBLANK(x),BLANK(),",
                "        If(x<0.95,-1,",
                "\t    If(x<1,0,1)",
                "    )",
                ")",
                ""
              ],
              "statusGraphic": "Traffic Light - Single",
              "targetExpression": "'Sales'[Last Year Sales]",
              "targetFormatString": "\\$#,0;(\\$#,0);\\$#,0"
            },
            "lineageTag": "dedc0174-5268-4401-84b8-5e4131a60ce2"
          }
        ],
        "partitions": [
          {
            "name": "Sales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"RetailBIDW\", [Query=\"SELECT s.[MonthID]+200 MonthID#(lf)      ,s.[ItemID]#(lf)      ,s.[LocationID]#(lf)      ,s.[Sum_GrossMarginAmount]#(lf)      ,s.[Sum_Regular_Sales_Dollars]#(lf)      ,s.[Sum_Markdown_Sales_Dollars]#(lf)      ,s.[Sum_Regular_Sales_Units]#(lf)      ,s.[Sum_Markdown_Sales_Units]#(lf)      ,s.[ScenarioID]#(lf)  FROM [dbo].[Monthly_sales] s tablesample (10 percent), IP.[Retail].[StoreDim] d #(lf)  where s.LocationID = d.[LocationID]#(lf) and MonthID+200>=concat(year(d.opendate ),RIGHT('0'+cast(month(d.opendate ) as varchar(2)), 2) )\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"MonthID\", \"MonthID\"}, {\"ItemID\", \"ItemID\"}, {\"LocationID\", \"LocationID\"}, {\"Sum_GrossMarginAmount\", \"Sum_GrossMarginAmount\"}, {\"Sum_Regular_Sales_Dollars\", \"Sum_Regular_Sales_Dollars\"}, {\"Sum_Markdown_Sales_Dollars\", \"Sum_Markdown_Sales_Dollars\"}, {\"ScenarioID\", \"ScenarioID\"}, {\"Sum_Regular_Sales_Units\", \"Sum_Regular_Sales_Units\"}, {\"Sum_Markdown_Sales_Units\", \"Sum_Markdown_Sales_Units\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"MonthID\", Int64.Type}, {\"ItemID\", Int64.Type}, {\"LocationID\", Int64.Type}, {\"Sum_GrossMarginAmount\", type number}, {\"Sum_Regular_Sales_Dollars\", type number}, {\"Sum_Markdown_Sales_Dollars\", type number}, {\"ScenarioID\", Int64.Type}, {\"Sum_Regular_Sales_Units\", type number}, {\"Sum_Markdown_Sales_Units\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Item",
        "columns": [
          {
            "name": "ItemID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "c04a55b0-1890-4a8d-be3e-0c52eb5b5ff1",
            "sourceColumn": "ItemID",
            "summarizeBy": "none"
          },
          {
            "name": "Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "22bb56b0-83a0-4742-8c1c-e7e10aef8f0b",
            "sourceColumn": "Segment",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Item\",\"TableItemName\":\"Category (clusters) 2\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "string",
            "lineageTag": "acb98098-0073-4a6b-89e5-56f8dafe3021",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Buyer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f43b2d40-1b64-4bc2-976e-bd7693377a72",
            "sourceColumn": "Buyer",
            "summarizeBy": "none"
          },
          {
            "name": "FamilyNane",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c352317e-a257-40b3-947b-aa7cf8edfb76",
            "sourceColumn": "FamilyNane",
            "summarizeBy": "none"
          },
          {
            "name": "Category (clusters) 2",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"i\",\"Entity\":\"Item\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"i\"}},\"Property\":\"Category\"}}],\"PartitionTable\":{\"Definition\":{\"TableDefinition\":{\"Version\":2,\"From\":[{\"Name\":\"i\",\"Entity\":\"Item\"},{\"Name\":\"s\",\"Entity\":\"Sales\"},{\"Name\":\"s1\",\"Entity\":\"Store\"}],\"Where\":[{\"Condition\":{\"Comparison\":{\"Left\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"s1\"}},\"Property\":\"Store Type\"}},\"Right\":{\"Literal\":{\"Value\":\"'New Store'\"}},\"ComparisonKind\":0}}},{\"Condition\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"s1\"}},\"Property\":\"PostalCode\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'37919'\"}}]]}}}],\"OrderBy\":[],\"Select\":[{\"Column\":{\"Expression\":{\"TransformTableRef\":{\"Source\":\"output0\"}},\"Property\":\"Item.Category\"},\"Name\":\"Item.Category\"},{\"Column\":{\"Expression\":{\"TransformTableRef\":{\"Source\":\"output0\"}},\"Property\":\"clusterId\"},\"Name\":\"clusterId\"}],\"GroupBy\":[],\"Transform\":[{\"Name\":\"KMeansClustering\",\"Algorithm\":\"KMeansClustering\",\"Input\":{\"Parameters\":[{\"Literal\":{\"Value\":\"-1L\"},\"Name\":\"NumberOfClusters\"}],\"Table\":{\"Name\":\"input0\",\"Columns\":[{\"Role\":\"Item\",\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"i\"}},\"Property\":\"Category\"},\"Name\":\"Item.Category\"}},{\"Role\":\"Attribute\",\"Expression\":{\"Measure\":{\"Expression\":{\"SourceRef\":{\"Source\":\"s\"}},\"Property\":\"Total Sales Variance %\"},\"Name\":\"Sales.Total Sales Variance %\"}},{\"Role\":\"Attribute\",\"Expression\":{\"Measure\":{\"Expression\":{\"SourceRef\":{\"Source\":\"s\"}},\"Property\":\"Avg $/Unit TY\"},\"Name\":\"Sales.Avg $/Unit TY\"}},{\"Role\":\"Attribute\",\"Expression\":{\"Measure\":{\"Expression\":{\"SourceRef\":{\"Source\":\"s\"}},\"Property\":\"This Year Sales\"},\"Name\":\"Sales.This Year Sales\"}}]}},\"Output\":{\"Table\":{\"Name\":\"output0\",\"Columns\":[{\"Expression\":{\"Column\":{\"Expression\":{\"TransformTableRef\":{\"Source\":\"input0\"}},\"Property\":\"Item.Category\"},\"Name\":\"Item.Category\"}},{\"Role\":\"Series\",\"Expression\":{\"TransformOutputRoleRef\":{\"Role\":\"ClusterId\"},\"Name\":\"clusterId\"}}]}}}]},\"ItemIdColumns\":[\"Item.Category\"],\"PartitionIdColumn\":\"clusterId\",\"Partitions\":[{\"PartitionIds\":[{\"Literal\":{\"Value\":\"null\"}}]}],\"DefaultPartitionPrefix\":\"Cluster\"},\"Result\":{\"TableName\":\"ClusterMappingTable 2\",\"PartitionIdColumn\":\"ClusterId\",\"ItemIdMappings\":[[{\"PartitionTableColumn\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Entity\":\"ClusterMappingTable 2\"}},\"Property\":\"Category\"}},\"SourceTableColumn\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Entity\":\"Item\"}},\"Property\":\"Category\"}}}]]}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Clusters for Category",
            "expression": [
              "VAR __ClusterValue = ",
              "  LOOKUPVALUE(",
              "    'ClusterMappingTable 2'[ClusterId],",
              "    'ClusterMappingTable 2'[Category],",
              "    'Item'[Category]",
              "  )",
              "",
              "RETURN",
              "  SWITCH(",
              "    __ClusterValue,",
              "    BLANK(),",
              "    BLANK(),",
              "    CONCATENATE(\"Cluster\", __ClusterValue)",
              "  )"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "Item"
                          }
                        },
                        "Property": "Category"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "e8b75fd8-a167-49da-97c0-724c569db3e2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "d844056b-47d9-4457-97d3-84fe5d073025",
        "partitions": [
          {
            "name": "Item",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"RetailBIDW\", [Query=\"SELECT [ItemID]#(lf)     -- ,[SupplierID]#(lf)      --,[Name]#(lf)      --,[Description]#(lf)      --,[BrandName]#(lf)      ,[ResponsibleBuyerLastName] +', ' + [ResponsibleBuyerFirstName] Buyer#(lf)      ,left([SegmentName], 4) [SegmentName]#(lf)     -- ,[SegmentID]#(lf)      ,left([FamilyName], 3) FamilyNane#(lf)    --  ,[FamilyID]#(lf)      ,[ClassName]#(lf)     -- ,[ClassID]#(lf)   --   ,[ItemCost]#(lf)     -- ,[OriginalItemCost]#(lf)  FROM [RetailBIDW].[dbo].[Item_Dimension]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"ItemID\", \"ItemID\"}, {\"SegmentName\", \"Segment\"}, {\"ClassName\", \"Category\"}, {\"Buyer\", \"Buyer\"}, {\"FamilyNane\", \"FamilyNane\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"ItemID\", Int64.Type}, {\"Segment\", type text}, {\"Category\", type text}, {\"Buyer\", type text}, {\"FamilyNane\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Time",
        "annotations": [
          {
            "name": "__PBI_LegacyCustomDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "ReportingPeriodID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "9a89d37d-1d78-4039-87d2-47791eb47fd0",
            "sourceColumn": "ReportingPeriodID",
            "summarizeBy": "none"
          },
          {
            "name": "Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "ed22c43e-ddd8-4208-9836-f3ca0452ed3a",
            "sourceColumn": "Period",
            "summarizeBy": "sum"
          },
          {
            "name": "FiscalYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "Year",
            "dataType": "int64",
            "lineageTag": "ea60fd43-2d9d-4ca6-baa0-6064824be0cd",
            "sourceColumn": "FiscalYear",
            "summarizeBy": "sum"
          },
          {
            "name": "FiscalMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Month",
            "dataType": "string",
            "lineageTag": "b092b02f-4352-49c5-8448-ac21b55b33ec",
            "sortByColumn": "Period",
            "sourceColumn": "FiscalMonth",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "m/d/yy",
            "isKey": true,
            "lineageTag": "8338e3fb-f793-4261-bd75-3698991b7c4b",
            "sourceColumn": "Month",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_2403841f-d1ed-4123-bf26-4ba8066f16d8"
                },
                "isDefault": true,
                "relationship": "ffdea654-6956-479d-9b81-f720c4647966"
              }
            ]
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "02873c55-97f7-426f-9383-442ff57c2696",
        "partitions": [
          {
            "name": "Time",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"RetailBIDW\", [Query=\"select distinct#(lf)concat(year(dateadd(year, 2, [BusinessDayDate] )),RIGHT('0'+cast(month(dateadd(year, 2, [BusinessDayDate] )) as varchar(2)), 2), RIGHT('0'+cast(day(dateadd(year, 2, [BusinessDayDate] )) as varchar(2)), 2) ) ReportingPeriodID, #(lf)  month(dateadd(year, 2, [BusinessDayDate] )) Period, #(lf)  left(DATENAME(month, dateadd(year, 2, [BusinessDayDate] )), 3) FiscalMonth, #(lf)  year(dateadd(year, 2, [BusinessDayDate] ) ) FiscalYear, #(lf)  dateadd(year, 2, [BusinessDayDate] ) [BusinessDayDate]#(lf)from [Time_Dimension]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"ReportingPeriodID\", \"ReportingPeriodID\"}, {\"Period\", \"Period\"}, {\"FiscalYear\", \"FiscalYear\"}, {\"FiscalMonth\", \"FiscalMonth\"}, {\"BusinessDayDate\", \"Month\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"ReportingPeriodID\", Int64.Type}, {\"Period\", Int64.Type}, {\"FiscalYear\", Int64.Type}, {\"FiscalMonth\", type text}, {\"Month\", type datetime}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "District",
        "columns": [
          {
            "name": "DistrictID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "263cda92-64e8-413c-8011-0ef587916c5c",
            "sourceColumn": "DistrictID",
            "summarizeBy": "none"
          },
          {
            "name": "District",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a2f1ba9-d9c3-48a5-b4a3-b637a16b74da",
            "sourceColumn": "District",
            "summarizeBy": "none"
          },
          {
            "name": "DM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDefaultLabel": true,
            "isKey": true,
            "keepUniqueRows": true,
            "lineageTag": "b261ab33-337b-44e9-b579-ccbdb6346590",
            "sourceColumn": "DM",
            "summarizeBy": "none"
          },
          {
            "name": "DM_Pic_fl",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "833bfcd9-d3f7-4163-bb0d-37a42462e6a3",
            "sourceColumn": "DM_Pic_fl",
            "summarizeBy": "none"
          },
          {
            "name": "DM_Pic",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "b4059d51-0265-43f8-9565-564ef719a552",
            "sourceColumn": "DM_Pic",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessUnitID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "ccaf01cb-9434-497f-9e3c-c4edbfb61493",
            "sourceColumn": "BusinessUnitID",
            "summarizeBy": "none"
          },
          {
            "name": "DMImage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "Image",
            "dataType": "binary",
            "isDefaultImage": true,
            "lineageTag": "845de3fa-2909-4e3c-a236-a6b995b8597c",
            "sourceColumn": "DMImage",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "636cd3a4-af99-4a62-bfc4-4a3d2eb162e1",
        "partitions": [
          {
            "name": "District",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"RetailBIDW\", [Query=\"SELECT [dbo].[District_Dimension].*   FROM [dbo].[District_Dimension]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"DistrictID\", \"DistrictID\"}, {\"DistrictName\", \"District\"}, {\"DM\", \"DM\"}, {\"DM_Pic_fl\", \"DM_Pic_fl\"}, {\"DM_Pic\", \"DM_Pic\"}, {\"BusinessUnitID\", \"BusinessUnitID\"}, {\"DMImage\", \"DMImage\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"DistrictID\", Int64.Type}, {\"District\", type text}, {\"DM\", type text}, {\"DM_Pic_fl\", type text}, {\"DM_Pic\", type text}, {\"BusinessUnitID\", Int64.Type}, {\"DMImage\", type binary}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_ca45d427-b349-4299-a604-253b0d3519f7",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6a79a694-c0f2-46aa-9aa6-714506baa69a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4b52a1bc-e18b-4773-8c83-4354b48c4f55",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "00f06728-ba90-4e37-89f7-4bee9248fd97",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1f03021a-4fc1-4dcf-988b-ddf1b0e654b8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2da3d154-2001-42c2-adee-f92cdf40a81a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bebff814-fa59-488a-93ae-f96e2a48b9f8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6a194535-1b6f-45d1-94c1-536aae68f7dd",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "80bac5b3-6841-4ceb-9e88-be956522ada4",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a2ced4a0-8d2f-42f6-8663-e88004b14212",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "a899807d-1948-4ecc-81cc-094d24df1a41",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "fc94c22f-eb26-4c0d-af2a-4bfe549cb26e",
                "ordinal": 3
              }
            ],
            "lineageTag": "3652f4ff-c23d-447f-8d00-74a2c8453afb"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "9e4207f9-81cf-41f7-b0a6-a74939ba8751",
        "partitions": [
          {
            "name": "DateTableTemplate_ca45d427-b349-4299-a604-253b0d3519f7-f50d4e29-d68e-4eea-9003-c26d181178d7",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_0eafa36c-5fc2-4b6f-84df-278a77695bc4",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "11d88d21-e536-40a5-99cd-4722caab7b06",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "38fe13d4-8215-487f-a3fc-80043a594487",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "15ba0ed2-64e9-429a-bde4-e7bd440acd31",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4bcb822e-a258-41fc-90e6-bf02d2115ece",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1a4e77b2-5e4b-4e7c-9e52-f257b65ed500",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "36091282-338a-4929-b603-17ef0292f433",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b3e02299-7ba0-417c-9a47-6f04ceeb9de5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "83447452-3a0a-4071-9f5a-1d2344d46ba5",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "4eb72d7e-6aa4-4207-91ca-c456f25d59a6",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "7e8603dd-e05f-4585-8f98-52a7da406c9d",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "72e03f97-ef91-4387-93b4-bf345e58de80",
                "ordinal": 3
              }
            ],
            "lineageTag": "29cd8ecc-86aa-457d-8e93-095dfffd6c93"
          }
        ],
        "isHidden": true,
        "lineageTag": "a19d996b-ce39-4a0f-83a9-826cf14a405e",
        "partitions": [
          {
            "name": "LocalDateTable_0eafa36c-5fc2-4b6f-84df-278a77695bc4-55cf8299-46c2-4857-bfd2-5f2d006bbe39",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Store'[OpenDate])), 1, 1), Date(Year(MAX('Store'[OpenDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_2403841f-d1ed-4123-bf26-4ba8066f16d8",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "734bade7-24c8-45c0-984a-172348c2e710",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "20450e5c-559c-4083-bada-ad8d13b6da02",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "495e817d-f08f-4703-b039-07e02661c639",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "14ca0605-b497-49fc-b043-7db7dc50ce2a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c8fbcc43-062f-4475-b526-64a3aa8c4146",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d8687472-e42f-4218-814a-ce706512fc09",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "54b4d9a1-871f-4d86-b64f-a6dc604ab17b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "99924a28-a569-47f5-9814-4ba38710ad68",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c327445a-9fae-43a6-b6f0-d117eb0dd552",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "133d0379-996b-47df-ad67-b0118ec0b62b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "67d13781-f2df-4e3b-93cb-877b6fe23c38",
                "ordinal": 3
              }
            ],
            "lineageTag": "bbe2b82a-0e2d-4f2c-8b61-1fd34bdc1891"
          }
        ],
        "isHidden": true,
        "lineageTag": "9a95b04c-87a8-4928-a96a-551b277020ae",
        "partitions": [
          {
            "name": "LocalDateTable_2403841f-d1ed-4123-bf26-4ba8066f16d8-210ecb21-c7a5-4359-8424-60d4683ea40c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Time'[Month])), 1, 1), Date(Year(MAX('Time'[Month])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "ClusterMappingTable 2",
        "annotations": [
          {
            "name": "ClusterMappingTable",
            "value": "true"
          },
          {
            "name": "__PBI_SemanticLinks",
            "value": "[{\"LinkTarget\":{\"TableName\":\"Item\",\"TableItemName\":\"Category (clusters) 2\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
          }
        ],
        "columns": [
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Item\",\"TableItemName\":\"Category (clusters) 2\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "17a11305-dec7-413e-862d-215c878abb66",
            "sourceColumn": "[Category]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ClusterId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Item\",\"TableItemName\":\"Category (clusters) 2\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "74f79be5-7072-4245-aae1-212e88cb70f8",
            "sourceColumn": "[ClusterId]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "46a25990-6d48-4040-9a0e-da60d1a611ce",
        "partitions": [
          {
            "name": "ClusterMappingTable 2-9e456a84-98b0-4e52-b4a4-90843dd9458d",
            "mode": "import",
            "source": {
              "expression": [
                "VAR __DS0FilterTable = ",
                "  FILTER(KEEPFILTERS(VALUES('Store'[Store Type])), 'Store'[Store Type] = \"New Store\")",
                "",
                "VAR __DS0FilterTable2 = ",
                "  TREATAS({\"37919\"}, 'Store'[PostalCode])",
                "",
                "VAR __DS0BodyPreTransform = ",
                "  SUMMARIZECOLUMNS(",
                "    'Item'[Category],",
                "    __DS0FilterTable,",
                "    __DS0FilterTable2,",
                "    \"Total_Sales_Variance__\", 'Sales'[Total Sales Variance %],",
                "    \"Avg___Unit_TY\", 'Sales'[Avg $/Unit TY],",
                "    \"This_Year_Sales\", 'Sales'[This Year Sales]",
                "  )",
                "",
                "VAR __DataTransformT0 = ",
                "  KMeansClustering(",
                "    SELECTCOLUMNS(",
                "      __DS0BodyPreTransform,",
                "      \"Category\", 'Item'[Category],",
                "      \"Total_Sales_Variance__\", [Total_Sales_Variance__],",
                "      \"Avg___Unit_TY\", [Avg___Unit_TY],",
                "      \"This_Year_Sales\", [This_Year_Sales]",
                "    ),",
                "    {(\"[Category]\", \"Item\"),",
                "      (\"[Total_Sales_Variance__]\", \"Attribute\"),",
                "      (\"[Avg___Unit_TY]\", \"Attribute\"),",
                "      (\"[This_Year_Sales]\", \"Attribute\")},",
                "    {(\"[Category]\", BLANK()),",
                "      (\"ClusterId\", \"ClusterId\")},",
                "    -1",
                "  )",
                "",
                "RETURN __DataTransformT0"
              ],
              "retainDataTillForceCalculate": true,
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}